language: objective-c
os: osx
osx_image: xcode10

script:
  - |
    set -o pipefail
    xcodebuild clean test -workspace RomanNumeralKit.xcworkspace -scheme RomanNumeralKit -destination 'platform=iOS Simulator,name=iPhone 5s,OS=12.0' -enableCodeCoverage YES | xcpretty