language: objective-c
osx_image: xcode9.4

branches:
  only:
    - mainline

xcode_project: RomanNumeralKit.xcodeproj
xcode_scheme: RomanNumeralKit
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 5s