language: objective-c
osx_image: xcode10

branches:
  only:
    - mainline

xcode_workspace: RomanNumeralKit.xcworkspace
xcode_scheme: RomanNumeralKit
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 5s