name: Test on all platforms

on:
  push:
    branches:    
      - mainline

jobs:

  test-on-iOS-13:
      name: Test on iOS 13
      runs-on: macOS-latest
      strategy:
          matrix:
            destination: ['OS=13.1,name=iPhone 11 Pro']
      steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Build & test w/ Debug configuration
          run: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            xcodebuild -scheme "${scheme}" -destination "${destination}" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
          env:
            DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
            destination: ${{ matrix.destination }}
            scheme: RomanNumeralKit
        - name: Send code coverage report to codecov.io
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            yml: ./codecov.yml

  test-on-macOS:
    name: Test on macOS
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['arch=x86_64']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build & test w/ Debug configuration
        run: |
          set -o pipefail
          xcodebuild -version
          xcodebuild -showsdks
          xcodebuild -scheme "${scheme}" -destination "${destination}" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
          destination: ${{ matrix.destination }}
          scheme: RomanNumeralKit
      - name: Send code coverage report to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: ./codecov.yml